services:
  - type: web
    name: gestion-guardias
    env: node
    plan: free
    repo: https://github.com/RGiskard7/gestion-guardias.git
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
